// Generated by ts-to-zod
import { z } from 'zod';

export const audioRecordTypeSchema = z.object({
  id: z.string(),
  audioUrl: z.string(),
  storagePath: z.string(),
  dictionaryEntryId: z.string().nullable(),
  audioUrlExpiresAt: z.iso.datetime().nullable(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
});
