version: '3.8'

services:
  db:
    image: postgres:15
    container_name: deepread_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deepread_server
    depends_on:
      - db
    ports:
      - "3002:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      OPENAI_MODEL: ${OPENAI_MODEL}
      OPENAI_PROJECT_ID: ${OPENAI_PROJECT_ID}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      FIREBASE_SERVICE_ACCOUNT_KEY_JSON: ${FIREBASE_SERVICE_ACCOUNT_KEY_JSON}
      GOOGLE_CREDENTIALS_JSON: ${GOOGLE_CREDENTIALS_JSON}
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
      PROJECT_NAME: ${PROJECT_NAME}
    volumes:
      - ./packages:/app/packages

volumes:
  postgres_data: