// Auto-generated by types/scripts/refactor-types.cjs. Do not edit manually.
export * from './audio-record.schema';
export * from './create-audio-record.schema';
export * from './update-audio-record.schema';
