// Generated by ts-to-zod
import { z } from 'zod';
import { dictionaryExampleTypeSchema } from '../../dictionary-examples/index.js';
import { audioRecordTypeSchema } from '../../audio-records/index.js';

export const dictionaryEntryTypeSchema = z.object({
  id: z.uuid(),
  text: z.string().min(1, 'Text is required'),
  transcription: z.string().min(1, 'Transcription is required'),
  pronounceVideoLinks: z.array(z.string()),
  examples: z.array(dictionaryExampleTypeSchema),
  audioRecords: z.array(audioRecordTypeSchema),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
});
