// Auto-generated by types/scripts/refactor-types.cjs. Do not edit manually.
export * from './create-dictionary-entry-with-example.body.schema';
export * from './create-dictionary-entry-with-example.response.schema';
export * from './create-dictionary-entry.schema';
export * from './dictionary-entry.schema';
export * from './find-or-create-dictionary-entry.response.schema';
export * from './get-dictionary-entry-with-examples-by-text.response.schema';
