/**
 * Automatically generated by script.
 * DO NOT EDIT MANUALLY. Use: ./scripts/generate-zod-config.sh
 */
export default [
  {
    name: "dictionaryExample",
    input: "src/lib/deep-read/dictionary-examples/interfaces/dictionary-example.interface.ts",
    output: "src/lib/deep-read/dictionary-examples/schemas/dictionary-example.schema.ts",
  },
  {
    name: "audioRecord",
    input: "src/lib/deep-read/audio-records/interfaces/audio-record.interface.ts",
    output: "src/lib/deep-read/audio-records/schemas/audio-record.schema.ts",
  },
  {
    name: "dictionaryEntry",
    input: "src/lib/deep-read/dictionary-entries/interfaces/dictionary-entry.interface.ts",
    output: "src/lib/deep-read/dictionary-entries/schemas/dictionary-entry.schema.ts",
  },
];
