// Generated by ts-to-zod
import { z } from 'zod';

export const dictionaryExampleTypeSchema = z.object({
  id: z.string(),
  example: z.string(),
  translation: z.string(),
  accent: z.string(),
  accentTranslation: z.string(),
  accentTranscription: z.string(),
  dictionaryEntryId: z.string(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
});
