// Generated by ts-to-zod
import { z } from 'zod';

import { dictionaryExampleTypeSchema } from '@deep-read/types/lib/deep-read/dictionary-examples';

export const getDictionaryExampleResponseTypeSchema =
  dictionaryExampleTypeSchema.pick({
    example: true,
    translation: true,
    accent: true,
    accentTranslation: true,
    accentTranscription: true,
  });

export type GetDictionaryExampleResponseType = z.infer<
  typeof getDictionaryExampleResponseTypeSchema
>;
