// Auto-generated by types/scripts/refactor-types.cjs. Do not edit manually.

export * as ai from './ai/index.js';
export * as audioRecords from './audio-records/index.js';
export * as dictionaryEntries from './dictionary-entries/index.js';
export * as dictionaryExamples from './dictionary-examples/index.js';
export * as tts from './tts/index.js';
