// Auto-generated by types/scripts/refactor-types.cjs. Do not edit manually.

export * as ai from './ai/index';
export * as audioRecords from './audio-records/index';
export * as dictionaryEntries from './dictionary-entries/index';
export * as dictionaryExamples from './dictionary-examples/index';
export * as tts from './tts/index';
