/**
 * ⚠️ auto-generated file - do not edit manually
 * 
 * This file was automatically copied from packages/server
 * using the sync-schemas-with-extension.js script.
 * 
 * To modify this schema, edit the source file in packages/server
 * and run: pnpm run sync:schemas
*/

// Generated by ts-to-zod
import { z } from 'zod';

export const audioRecordTypeSchema = z.object({
  id: z.uuid(),
  audioUrl: z.url().min(1, 'Audio URL cannot be empty'),
  storagePath: z.string().min(1, 'Storage path cannot be empty'),
  dictionaryEntryId: z.uuid().nullable(),
  audioUrlExpiresAt: z.iso.datetime().nullable(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
});

export type AudioRecordType = z.infer<typeof audioRecordTypeSchema>;
