/**
 * ⚠️ auto-generated file - do not edit manually
 * 
 * This file was automatically copied from packages/server
 * using the sync-schemas-with-extension.js script.
 * 
 * To modify this schema, edit the source file in packages/server
 * and run: pnpm run sync:schemas
*/

// Generated by ts-to-zod
import { z } from 'zod';

import { audioRecordTypeSchema } from './audio-record.schema';
import { dictionaryExampleTypeSchema } from './dictionary-example.schema';

export const dictionaryEntryTypeSchema = z.object({
  id: z.uuid(),
  text: z.string().min(1, 'Text is required'),
  transcription: z.string().min(1, 'Transcription is required'),
  pronounceVideoLinks: z.array(z.string()),
  examples: z.array(dictionaryExampleTypeSchema),
  audioRecords: z.array(audioRecordTypeSchema),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
});

export type DictionaryEntryType = z.infer<typeof dictionaryEntryTypeSchema>;
