/**
 * ⚠️ auto-generated file - do not edit manually
 * 
 * This file was automatically copied from packages/server
 * using the sync-schemas-with-extension.js script.
 * 
 * To modify this schema, edit the source file in packages/server
 * and run: pnpm run sync:schemas
*/

// Generated by ts-to-zod
import { z } from 'zod';

export const dictionaryExampleTypeSchema = z.object({
  id: z.uuid(),
  example: z.string().min(1, 'Example is required'),
  translation: z.string().min(1, 'Translation is required'),
  accent: z.string().min(1, 'Accent is required'),
  accentTranslation: z.string().min(1, 'Accent translation is required'),
  accentTranscription: z.string().min(1, 'Accent transcription is required'),
  dictionaryEntryId: z.uuid(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
});

export type DictionaryExampleType = z.infer<typeof dictionaryExampleTypeSchema>;
