/**
 * ⚠️ auto-generated file - do not edit manually
 * 
 * This file was automatically copied from packages/server
 * using the sync-schemas-with-extension.js script.
 * 
 * To modify this schema, edit the source file in packages/server
 * and run: pnpm run sync:schemas
*/

// Generated by ts-to-zod
import { z } from 'zod';
import { dictionaryExampleTypeSchema } from './dictionary-example.schema';

export const getDictionaryExampleResponseTypeSchema =
  dictionaryExampleTypeSchema.pick({
    example: true,
    translation: true,
    accent: true,
    accentTranslation: true,
    accentTranscription: true,
  });

export type GetDictionaryExampleResponseType = z.infer<
  typeof getDictionaryExampleResponseTypeSchema
>;
