// Auto-generated by types/scripts/refactor-types.cjs. Do not edit manually.
export * from './create-dictionary-example.schema';
export * from './dictionary-example.schema';
export * from './get-dictionary-example.response.schema';
